apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-worker-17301
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-worker-17301
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
